Ejercicio 1
Crea un programa que lea una secuencia de caracteres, guarde cada caracter en una posición de una lista y
finalmente muestre la secuencia invertida.

In [5]:
n = int(input("Introduzca el número de caracteres que desea ingresar: "))
lista = []
for i in range(n):
  lista.append(input())
lista.reverse()
print(lista)



Introduzca el número de caracteres que desea ingresar: 7
a
b
c
d
f
g
h
['h', 'g', 'f', 'd', 'c', 'b', 'a']


Ejercicio 2
Crea un programa que lea dos strings de la misma longitud, los guarde intercalados en una lista. Por último,
mostrar el contenido de la lista.
Por ejemplo, si introducimos hola caracola y adios marieta, debería mostrarse haodleao sc
amraarcioeltaa.

In [11]:
palabra1 = input("Introduzca la primer palabra: ")
palabra2 = input("Introduczca la segunda palabra: ")
n = len(palabra1)
m = len(palabra2)
cont1, cont2 = 0,0
lista = []
if n == m:
  for i in range(2*n):
    if i%2 == 0:
      lista.append(palabra1[cont1])
      cont1 += 1
    else:
      lista.append(palabra2[cont2])
      cont2 += 1
else:
  print("Las palabras deben tener la misma longitud")
print(lista)

Introduzca la primer palabra: hola caracola
Introduczca la segunda palabra: adios marieta
['h', 'a', 'o', 'd', 'l', 'i', 'a', 'o', ' ', 's', 'c', ' ', 'a', 'm', 'r', 'a', 'a', 'r', 'c', 'i', 'o', 'e', 'l', 't', 'a', 'a']


Ejercicio 3
Crea un programa que lea un string y guarde en una lista todas las consonantes.

In [19]:
palabra = input("Introduzca un string: ")
S = palabra.lower()
lista = []
for i in range(len(S)):
  if S[i] != 'a' and S[i] != 'e' and S[i] != 'i' and S[i] != 'o' and S[i] != 'u':
    lista.append(palabra[i])
print(lista)


Introduzca un string: ABA
['B']


Ejercicio 4
Crea un programa que lea una palabra, la guarde en una lista y compruebe si se trata de un palíndromo.

In [27]:
palabra = input("Introduzca una palabra: ")
lista= []
es_palindroma = True
for j in range(len(palabra)):
  lista.append(palabra[j])
for i in range (len(palabra)):
  if lista[i] != lista[len(palabra)-i-1]:
    es_palindroma = False
    break
if (es_palindroma == True):
  print("La palabra es palindroma")
else:
  print("La palabra no es palindroma")

Introduzca una palabra: anita
La palabra no es palindroma


Ejercicio 5
Crea un programa que lea una matriz 3 x 3 y devuelva el máximo de cada fila.

In [39]:
M = []
maximos = []
for i in range(3):
  M.append([])
  for j in range(3):
    M[i].append(int(input()))

for i in range(3):
  max = M[i][0]
  for j in range(2):
      if max <= M[i][j+1]:
        max = M[i][j+1]
  maximos.append(max) 

for i in range(3):
  print("El valor máximo de la fila {} es {}".format(i+1,maximos[i]))

-1
-2
-3
10
-10
0
-3
4
-12
El valor máximo de la fila 1 es -1
El valor máximo de la fila 2 es 10
El valor máximo de la fila 3 es 4


Ejercicio 6
Crea un programa que lea un entero, n, de teclado y construya una matriz de tamaño n × n. Cada posición
debe contener su orden en la matriz (desde 0 hasta n
2 − 1. Por ejemplo, si n es 3, deberá crearse la matriz
[0, 1, 2]
[3, 4, 5]
[6, 7, 8]

In [40]:
n = int(input("Ingrese la deimensión de la matriz: "))
M = []
cont = 0
for i in range(n):
  M.append([])
  for j in range(n):
    M[i].append(cont)
    cont += 1
print(M)


Ingrese la deimensión de la matriz: 3
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


Ejercicio 7
Crea una matriz de n × m y asigna los valores manualmente. El programa debe indicar si la suma de cada
columna es el mismo valor

In [50]:
n = int(input("Introduzca el número de filas de la matriz: "))
m = int(input("Introduzca el número de columnas de la matriz: "))
M = []
es_suma_igual = True

for i in range(n):
  M.append([])
  for j in range (m):
    M[i].append(int(input()))

lista= []
for i in range(m):
  suma=0
  for j in range(n):
    suma =suma + M[j][i]
  lista.append(suma)
print(lista)

for i in range(m-1):
  if lista[i] != lista[i+1]:
    es_suma_igual = False
    break

if es_suma_igual == True:
  print("La suma de cada columna tiene el mismo valor: {}".format(lista[0]))
else:
  print("La suma de cada columna no tiene el mismo valor")




Introduzca el número de filas de la matriz: 2
Introduzca el número de columnas de la matriz: 3
4
5
7
6
5
3
[10, 10, 10]
La suma de cada columna tiene el mismo valor: 10


Ejercicio 8
Crear un programa determina si la matriz introducida manualmente (tanto sus dimensiones como los elementos) se trata de la matriz identidad. Recuerda que la matriz identidad debe ser una matriz cuadrada.

In [57]:
n = int(input("Introduzca la dimensión de la matriz: "))
M = []
identidad = []
es_identidad = True

for i in range(n):
  M.append([])
  identidad.append([])
  for j in range(n):
    M[i].append(int(input()))
    if i == j:
      identidad[i].append(1)
    else:
      identidad[i].append(0)

for i in range(n):
  for j in range(n):
    if M[i][j] != identidad[i][j]:
      es_identidad = False
      break

if es_identidad == True:
  print("La matriz que introdujo es la matriz identidad")
else:
  print("La matriz que introdujo no es la matriz identidad")

Introduzca la dimensión de la matriz: 3
1
0
0
0
1
0
0
0
1
La matriz que introdujo es la matriz identidad


Ejercicio 9
Realiza un programa que calcule la matriz transpuesta

In [60]:
n = int(input("Introduzca el número de filas: "))
m = int(input("Introduzca el número de columnas: "))
M = []

for i in range(n):
  M.append([])
  for j in range(m):
    M[i].append(int(input()))

trans = []

for i in range(m):
  trans.append([])
  for j in range(n):
    trans[i].append(M[j][i])
    print(trans[i][j], end=" ")
  print("")


Introduzca el número de filas: 2
Introduzca el número de columnas: 4
2
3
5
6
7
8
9
10
2 7 
3 8 
5 9 
6 10 


Ejercicio 10
Crea un programa que pida al usuario la dimensión y cree la matriz identidad de orden correspondiente con
numpy.

In [62]:
import numpy as np
n = int(input("Introduzca la dimensión de la matriz: "))
I = np.zeros((n,n))
for i in range(n):
  for j in range(n):
    if i == j:
      I[i][j] = 1
print(I)

Introduzca la dimensión de la matriz: 5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
